genernal:
  label: 基本设置
  items:
    index_notice:
      name: index_notice
      label: 首页公告
      type: textarea
      default: '不以物喜不以己悲' 
    profile_desc:
      name: profile_desc               
      label: 侧边栏个人信息卡片描述              
      type: text                
      placeholder: '一些描述...'     
    music:
      name: music
      label: 音乐（为空不显示图标）
      type: textarea
      placeholder: '歌曲链接1#*#歌曲名称,歌曲链接2#*#歌曲名称'
    github:
      name: github               
      label: github              
      type: text                
      placeholder: 'github个人主页链接'       
    email:
      name: email               
      label: 邮箱              
      type: text                
      placeholder: '个人邮箱'      
    record:
      name: record
      label: ICP备案号
      type: text
      placeholder: '填写ICP备案号'
    record2img:
      name: record2img               
      label: 备案图标              
      type: attachment               
      placeholder: '公安备案图标地址'           
      default: 'https://b2.bmp.ovh/imgs/2019/09/a46fc5b15b3363ff.png'  
    record2:
      name: record2
      label: 公安备案号
      type: text
      placeholder: '填写公安备案号'

style:
  label: 样式设置
  items:
    mdui_theme:
      name: mdui_theme
      label: 主题色
      type: select
      default: 'mdui-theme-primary-blue'
      options:
        - value: 'mdui-theme-primary-blue'
          label: '蓝'
        - value: 'mdui-theme-primary-green'
          label: '绿'
        - value: 'mdui-theme-primary-red'
          label: '红'
        - value: 'mdui-theme-primary-pink'
          label: '粉'
        - value: 'mdui-theme-primary-purple'
          label: '紫'
        - value: 'mdui-theme-primary-orange'
          label: '橘'
        - value: 'mdui-theme-primary-blue-grey'
          label: '灰'
        - value: 'mdui-theme-primary-brown'
          label: '棕'
        - value: 'mdui-theme-primary-cyan'
          label: '青'
    indeximg:
      name: indeximg               
      label: 镇站图              
      type: attachment               
      placeholder: '图片地址'           
      default: ''  
    bvideo_enabled:
      name: bvideo_enabled
      label: 镇站视频
      type: radio
      data-type: bool
      default: false
      description: '开启后，镇站图将会成为视频封面，默认为 false'
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    bvideoLink:
      name: bvideoLink               
      label: 视频url              
      type: attachment               
      placeholder: '请填入视频url'           
      default: ''                          
    drawimg:
      name: drawimg               
      label: 抽屉图              
      type: attachment               
      placeholder: '图片地址'           
      default: ''     
    mdui_icons:
      name: mdui_icons
      label: 字体图标样式
      type: select
      default: 'MI'
      options:
        - value: 'MI'
          label: 'Material-Icons'
        - value: 'MIO'
          label: 'Material Icons Outlined' 
    code_css:
      name: code_css
      label: 代码样式
      type: select
      default: 'default'
      data-type: string
      options:
        - value: "agate"
          label: "agate"
        - value: "androidstudio"
          label: "androidstudio"
        - value: "atom-one-dark"
          label: "atom-one-dark"
        - value: "default"
          label: "default"
        - value: "github"
          label: "github"
        - value: "github-dark"
          label: "github-dark"
        - value: "gradient-dark"
          label: "gradient-dark"
        - value: "gradient-light"
          label: "gradient-light"
        - value: "nord"
          label: "nord"
        - value: "/base16/nova"
          label: "nova"
        - value: "paraiso-light"
          label: "paraiso-light"
        - value: "/base16/material"
          label: "material"
    comment_style:
      name: comment_style
      label: 评论模块样式
      type: select
      default: '样式1'
      data-type: string
      options:
        - value: "comment1"
          label: "样式1"
        - value: "comment2"
          label: "样式2"
        
others:
  label: 其他
  items:
    ad_enabled:
      name: ad_enabled
      label: 侧边栏广告
      type: radio
      data-type: bool
      default: false
      description: '是否开启侧边栏广告，默认为 false'
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    adimg:
      name: adimg               
      label: 广告图片              
      type: attachment               
      placeholder: '图片地址'           
      default: ''               
    adlink:
      name: adlink
      label: 广告链接
      type: text
      placeholder: '填写广告链接'